# In Class Assignment: 1

**Team: Trace Smith and Robert Flamenbaum** 

________________________________________________________________________________________________________

- In the following assignment you will be asked to fill in python code and derivations for a number of different problems. Please read all instructions carefully and turn in the rendered notebook (or HTML of the rendered notebook)  before the end of class (or right after class). The initial portion of this notebook is given before class and the remainder is given during class. Please answer the initial questions before class. Once class has started you may rework your answers as a team for the initial part of the assignment. 

## Contents

* <a href="#Loading">Loading the Data</a>
* <a href="#linearnumpy">Linear Regression</a>

**These portions are not yet accessible until the start of class:**
* <a href="#sklearn">Using Scikit Learn for Regression</a>
* <a href="#classification">Linear Classification</a>

________________________________________________________________________________________________________
### Python Packages

In [18]:
from sklearn.datasets import load_diabetes
import numpy as np
import pandas as pd
#Enable HTML/CSS 
from IPython.core.display import HTML
HTML("<link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'><style>div.attn { font-family: 'Helvetica Neue'; font-size: 30px; line-height: 40px; color: #FFFFFF; text-align: center; margin: 30px 0; border-width: 10px 0; border-style: solid; border-color: #5AAAAA; padding: 30px 0; background-color: #DDDDFF; }hr { border: 0; background-color: #ffffff; border-top: 1px solid black; }hr.major { border-top: 10px solid #5AAA5A; }hr.minor { border: none; background-color: #ffffff; border-top: 5px dotted #CC3333; }div.bubble { width: 65%; padding: 20px; background: #DDDDDD; border-radius: 15px; margin: 0 auto; font-style: italic; color: #f00; }em { color: #AAA; }div.c1{visibility:hidden;margin:0;height:0;}div.note{color:red;}</style>")

________________________________________________________________________________________________________
<a id="Loading"></a>
## Loading the Data

- Please run the following code to read in the "diabetes" dataset from sklearn's data loading module. This will load the data into the variable `ds`. `ds` is a dictionary object with fields like `ds.data`, which is a matrix of the continuous features in the dataset. The object is not a pandas dataframe. It is a numpy matrix. Each row is a set of observed instances, each column is a different feature. It also has a field called `ds.target` that is a continuous value we are trying to predict. Each entry in `ds.target` is a label for each row of the `ds.data` matrix. 

In [29]:
#Get Diabetes Dataset
ds = load_diabetes()
X = ds.data
y = ds.target

print('Dataset Dimensions: Columns -- {} Rows --{}'.format(X.shape[1],X.shape[0]))
print('Target Dimensions: Rows -- {}'.format(y.shape[0]))
print('Target Range:', np.min(y),np.max(y))

Dataset Dimensions: Columns -- 10 Rows --442
Target Dimensions: Rows -- 442
Target Range: 25.0 346.0


In [30]:
X[:5,:]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632783, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567061, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286377, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665645,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02269202, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187235,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03199144, -0.04664087]])

In [31]:
y[:5]

array([ 151.,   75.,  141.,  206.,  135.])

________________________________________________________________________________________________________
<a id="linearnumpy"></a>
## Using Linear Regression 

In the videos, we derived the formula for calculating the optimal values of the regression weights:

$$ w = (X^TX)^{-1}X^Ty $$

Where $X$ is the matrix of values with a bias column of ones appended onto it. For the diabetes dataset one could construct this $X$ matrix by stacking a column of ones onto the `ds.data` matrix. 

$$ X=\begin{bmatrix}
         & \vdots &        &  1 \\
        \dotsb & \text{ds.data} & \dotsb &  \vdots\\
         & \vdots &         &  1\\
     \end{bmatrix}
$$

**Question 1:** For the diabetes dataset, how many elements will the vector $w$ contain?

In [74]:
print('X Transpose Shape:',np.transpose(X).shape)
print('X Shape:',X.shape)
print('Yields:','10x10\n')

print('X Transpose Shape:',np.transpose(X).shape)
print('Target Shape:',target.shape)
print('Yeilds:','10x1\n')

print('Dimensions of W: ','10x1')
print('Final Dimensions of W including Bias Term: ','11x1')

X Transpose Shape: (10, 442)
X Shape: (442, 10)
Yields: 10x10

X Transpose Shape: (10, 442)
Target Shape: (442,)
Yeilds: 10x1

Dimensions of W:  10x1
Final Dimensions of W including Bias Term:  11x1


________________________________________________________________________________________________________

**Exercise 1:** In the following empty cell, use this equation and numpy matrix operations to find the values of the vector $w$. You will need to be sure $X$ and $y$ are created like the instructor talked about in the video. Don't forget to include any modifications to $X$ to account for the bias term in $w$. You might be interested in the following functions:

- `np.hstack((mat1,mat2))` stack two matrices horizontally, to create a new matrix
- `np.ones((rows,cols))` create a matrix full of ones
- `my_mat.T` takes transpose of numpy matrix named `my_mat`
- `np.dot(mat1,mat2)` or `mat1 @ mat2` is matrix multiplication for two matrices
- `np.linalg.inv(mat)` gets the inverse of the variable `mat`

In [21]:
# Write you code here, print the values of the regression weights using the 'print()' function in python


[[ -10.01219782]
 [-239.81908937]
 [ 519.83978679]
 [ 324.39042769]
 [-792.18416163]
 [ 476.74583782]
 [ 101.04457032]
 [ 177.06417623]
 [ 751.27932109]
 [  67.62538639]
 [ 152.13348416]]
